/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HV6feINmvW6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function AdBanner() {
  return (
    <div className="bg-[#f9d6e4] p-4 flex items-center justify-between rounded-lg">
      <div className="flex flex-col">
        <span className="text-2xl font-bold text-[#bd1e59]">Sweet Deserts</span>
        <span className="text-sm text-[#bd1e59]">You will Love Our Donuts</span>
      </div>
      <div className="flex space-x-2">
        <img
          alt="Donut"
          className="rounded-full"
          height="80"
          src="/donuts.webp"
          style={{
            aspectRatio: "80/80",
            objectFit: "cover",
          }}
          width="80"
        />
        <img
          alt="Donut"
          className="rounded-full"
          height="80"
          src="/donuts2.webp"
          style={{
            aspectRatio: "80/80",
            objectFit: "cover",
          }}
          width="80"
        />
        <img
          alt="Donut"
          className="rounded-full"
          height="80"
          src="/donuts3.jpg"
          style={{
            aspectRatio: "80/80",
            objectFit: "cover",
          }}
          width="80"
        />
      </div>
      <Button className="bg-[#ffffff] text-[#bd1e59] font-bold py-2 px-4 rounded-lg">ORDER</Button>
    </div>
  )
}
