/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/J2G090NGnnp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function DailyPoints() {
  return (
    <div className="flex justify-between p-4 bg-white rounded-lg shadow">
      <div className="flex flex-col justify-between">
        <h2 className="text-2xl font-bold">Referral Clicks</h2>
        <p className="text-gray-600">
          You have not done enough clicks today to get referral points. you have to do at least 40 click.
        </p>
      </div>
      <div className="flex flex-col items-center justify-center bg-[#00ff7f] text-white rounded-lg p-4">
        <span className="text-6xl font-bold">200</span>
        <span className="text-2xl font-bold">Point</span>
        <span className="text-lg font-semibold">40 / 40</span>
      </div>
    </div>
  )
}
