/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/AiERiRgFdeW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "./ui/dialog"
import { ContactForm } from "./contact-form"
import { useState } from "react"
import { ChevronDownIcon } from "lucide-react"

export function Footer() {

  const [openIndexes, setOpenIndexes] = useState<number[]>([])
  const toggleOpen = (index: number) => {
    if (openIndexes.includes(index)) {
      setOpenIndexes(openIndexes.filter((i) => i !== index))
    } else {
      setOpenIndexes([...openIndexes, index])
    }
  }
  return (
    <>
      <footer className="bg-[#f8f9fa] p-4 relative overflow-hidden">
        {/* <div className="bg-[url('/footerbg.png?height=1200&width=1920')] bg-cover bg-center absolute inset-0 opacity-10" /> */}
        <div className="max-w-7xl mx-auto flex items-center justify-between relative z-10">
          <img
            alt="Logo"
            className="h-10"
            height="40"
            src="/wildloud-logo.png"
            style={{
              aspectRatio: "200/40",
              objectFit: "cover",
            }}
            width="200"
          />
          <nav className="flex space-x-4">
            <Link className="text-gray-600 hover:text-gray-800" href="#">
              Guide
            </Link>
            <Link className="text-gray-600 hover:text-gray-800" href="#">
              Sitemap
            </Link>
            <Link className="text-gray-600 hover:text-gray-800" href="#">
              Terms & Conditions
            </Link>


          </nav>
          <div className="flex flex-row gap-2">
            {/* Contact Dialog */}
            <Dialog>
              <DialogTrigger asChild>
                <Button className="bg-[#34d399] text-white" >Contact</Button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-[425px]">
                <div className="mb-4">
                  <img
                    alt="Decorative header"
                    className="w-full h-auto rounded-lg mb-4"
                    height="150"
                    src="/contactbg.png"
                    style={{
                      aspectRatio: "300/150",
                      objectFit: "cover",
                    }}
                    width="300"
                  />
                  <h2 className="text-3xl font-bold text-center mb-4">Contact Us</h2>
                  <p className="text-center text-sm mb-8">Have any questions or suggestion? We&apos;d love to hear from you.</p>
                </div>
                <form className="space-y-6">
                  <div>
                    <label className="block text-sm font-medium mb-2" htmlFor="username">
                      Username
                    </label>
                    <input
                      className="w-full border-b-2 border-gray-300 focus:outline-none focus:border-green-500"
                      id="username"
                      placeholder="Loreen Larm#3843"
                      type="text"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-2" htmlFor="email">
                      Email
                    </label>
                    <input
                      className="w-full border-b-2 border-gray-300 focus:outline-none focus:border-green-500"
                      id="email"
                      placeholder="Enter email address"
                      type="email"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-2" htmlFor="title">
                      Title
                    </label>
                    <input
                      className="w-full border-b-2 border-gray-300 focus:outline-none focus:border-green-500"
                      id="title"
                      placeholder="Your Comment Title"
                      type="text"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium mb-2" htmlFor="message">
                      Message
                    </label>
                    <textarea
                      className="w-full border-b-2 border-gray-300 focus:outline-none focus:border-green-500"
                      id="message"
                      placeholder="Your Comment"
                      rows={4}
                    />
                  </div>
                  <button
                    className="w-full bg-green-500 text-white font-bold py-2 px-4 rounded hover:bg-green-600 focus:outline-none focus:shadow-outline"
                    type="submit"
                  >
                    Submit
                  </button>
                </form>
              </DialogContent>
            </Dialog>
            {/* FAQ Dialog */}
            <Dialog >
              <DialogTrigger asChild>
                <Button className="bg-[#34d399] text-white" >FAQ</Button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-[425px]">
                <img
                  alt="Decorative header"
                  className="w-full h-auto rounded-lg mb-4"
                  height="150"
                  src="/contactbg.png"
                  style={{
                    aspectRatio: "300/150",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <DialogHeader>
                  <DialogTitle>Frequently Asked Questions</DialogTitle>
                </DialogHeader>
                <div className="space-y-4">
                  <div className="space-y-2">
                    <Button variant="ghost" className="justify-between w-full text-left" onClick={() => toggleOpen(0)}>
                      What is the price of this service?
                      <ChevronDownIcon className="w-5 h-5" />
                    </Button>
                    {openIndexes.includes(0) && (
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.
                      </p>
                    )}
                  </div>
                  <div className="space-y-2">
                    <Button variant="ghost" className="justify-between w-full text-left" onClick={() => toggleOpen(1)}>
                      What is the price of this service?
                      <ChevronDownIcon className="w-5 h-5" />
                    </Button>
                    {openIndexes.includes(1) && (
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.
                      </p>
                    )}
                  </div>
                  <div className="space-y-2">
                    <Button variant="ghost" className="justify-between w-full text-left" onClick={() => toggleOpen(2)}>
                      What is the price of this service?
                      <ChevronDownIcon className="w-5 h-5" />
                    </Button>
                    {openIndexes.includes(2) && (
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.
                      </p>
                    )}
                  </div>
                  <div className="space-y-2">
                    <Button variant="ghost" className="justify-between w-full text-left" onClick={() => toggleOpen(3)}>
                      What is the price of this service?
                      <ChevronDownIcon className="w-5 h-5" />
                    </Button>
                    {openIndexes.includes(3) && (
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.
                      </p>
                    )}
                  </div>
                  <div className="space-y-2">
                    <Button variant="ghost" className="justify-between w-full text-left" onClick={() => toggleOpen(4)}>
                      What is the price of this service?
                      <ChevronDownIcon className="w-5 h-5" />
                    </Button>
                    {openIndexes.includes(4) && (
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.
                      </p>
                    )}
                  </div>
                  <div className="space-y-2">
                    <Button variant="ghost" className="justify-between w-full text-left" onClick={() => toggleOpen(5)}>
                      What is the price of this service?
                      <ChevronDownIcon className="w-5 h-5" />
                    </Button>
                    {openIndexes.includes(5) && (
                      <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                        dolore magna aliqua.
                      </p>
                    )}
                  </div>
                </div>
              </DialogContent>
            </Dialog>
          </div>

          {/* contact dialog */}

          {/* FAQ Dialog */}

        </div>

        <div className="flex flex-row">
          <img
            src="/footerbg.png"
            className="w-full h-40"
          />
        </div>
      </footer>
    </>

  )
}
