/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0q9igkzorIW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { CardContent, Card } from "@/components/ui/card"
import { MedalIcon, MousePointerClickIcon, } from "lucide-react"

export function HomeSection1() {
  return (
    <div className="flex space-x-4">
      <Card className="w-[350px]">
        <CardContent className="flex flex-col items-center p-6">
          <MousePointerClickIcon className="h-12 w-12 text-black" />
          <p className="mt-2 text-sm font-medium">Total Hits</p>
          <p className="text-4xl font-bold">9215</p>
        </CardContent>
      </Card>
      <Card className="w-[350px]">
        <CardContent className="flex flex-col items-center p-6">
          <MedalIcon className="h-12 w-12 text-black" />
          <p className="mt-2 text-sm font-medium">Your Place</p>
          <p className="text-4xl font-bold">921Th</p>
        </CardContent>
      </Card>
      <Card className="w-[350px]">
        <CardContent className="flex flex-col items-center p-6">
          <MedalIcon className="h-12 w-12 text-black" />
          <p className="mt-2 text-sm font-medium">Click Credit</p>
          <p className="text-4xl font-bold">921Th</p>
        </CardContent>
      </Card>
    </div>
  )
}
