/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SdkfTGcZXoT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { useEffect, useRef, useState } from "react";

import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"

import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"
import { ProgressSpinner } from 'primereact/progressspinner';
const formSchema = z.object({
  url: z.string().url(),
  platform: z.string(),
})
export function HomeSection2() {
  const [isLinkOpened, setIsLinkOpened] = useState(false);
  const [timer, setTimer] = useState(null);
  const [isSubmitting, setIsSubmitting] = useState(false)
  const activityTimeout = useRef<NodeJS.Timeout | null>(null);
  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
  })
  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsSubmitting(true)
    setTimeout(() => {
      console.log(values)
      setIsSubmitting(false)
    }, 1000);

    // form.reset()
  }
  useEffect(() => {
    if (isLinkOpened) {
      console.log('User opened the video link');
      activityTimeout.current = setTimeout(() => {
        console.log('User has been on the page for 30 seconds after opening the link');
      }, 5000);
    }

    return () => {
      if (activityTimeout.current) {
        clearTimeout(activityTimeout.current);
      }
    };
  }, [isLinkOpened]);

  const handleLinkClick = () => {
    setIsLinkOpened(true);
  };
  return (
    <div className="bg-white p-8">
      <h2 className="text-3xl font-bold mb-6">Your Submits</h2>
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
          <FormField
            control={form.control}
            name="url"
            render={({ field }) => (
              <FormItem>
                <FormLabel>url</FormLabel>
                <FormControl>
                  <Input type="text" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name="platform"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Platform</FormLabel>
                <Select onValueChange={field.onChange} defaultValue={field.value}>
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Platform" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    <SelectItem value="fb">Facebook</SelectItem>
                    <SelectItem value="yt">Youtube</SelectItem>
                    <SelectItem value="x">X</SelectItem>
                  </SelectContent>
                </Select>
                <FormMessage />
              </FormItem>
            )}
          />
          <div className="flex flex-row justify-between">
            {!isSubmitting ? (
              <Button type="submit">
                Submit
              </Button>
            ) :
              <>
                <Button >
                  <ProgressSpinner
                    style={{ width: '50px', height: '50px' }}
                    animationDuration=".4s"
                  />
                </Button>
              </>
            }
          </div>
        </form>
      </Form>
      {/*
      <div className="grid grid-cols-3 gap-4 items-end">
        <div>
          <label className="block mb-2 text-sm font-medium text-gray-900" htmlFor="type">
            Type
          </label>
          <Select>
            <SelectTrigger id="type">
              <SelectValue placeholder="Twitter" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="twitter">Twitter</SelectItem>
              <SelectItem value="facebook">Facebook</SelectItem>
              <SelectItem value="instagram">Instagram</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <Input id="url-account" placeholder="Url/account" />
        <Button className="bg-[#34D399] text-white">Submit</Button>
      </div> */}
      {/* <div className="grid grid-cols-3 gap-4 items-center mt-4">
        <div>
          <label className="block mb-2 text-sm font-medium text-gray-900" htmlFor="total-clicks">
            Total Clicks
          </label>
          <div className="flex">
            <Switch className="mr-2" id="total-clicks-on" />
            <Switch id="total-clicks-off" />
          </div>
        </div>
        <div>
          <label className="block mb-2 text-sm font-medium text-gray-900" htmlFor="daily-clicks">
            Daily Clicks
          </label>
          <div className="flex">
            <Switch className="mr-2" id="daily-clicks-on" />
            <Switch id="daily-clicks-off" />
          </div>
        </div>
        <Input id="points" placeholder="Points" />
      </div>
      */}
    </div>
  )
}
