/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SdkfTGcZXoT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"

export function HomeSection2() {
  return (
    <div className="bg-white p-8">
      <h2 className="text-3xl font-bold mb-6">Your Submits</h2>
      <div className="grid grid-cols-3 gap-4 items-end">
        <div>
          <label className="block mb-2 text-sm font-medium text-gray-900" htmlFor="type">
            Type
          </label>
          <Select>
            <SelectTrigger id="type">
              <SelectValue placeholder="Twitter" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="twitter">Twitter</SelectItem>
              <SelectItem value="facebook">Facebook</SelectItem>
              <SelectItem value="instagram">Instagram</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <Input id="url-account" placeholder="Url/account" />
        <Button className="bg-[#34D399] text-white">Submit</Button>
      </div>
      <div className="grid grid-cols-3 gap-4 items-center mt-4">
        <div>
          <label className="block mb-2 text-sm font-medium text-gray-900" htmlFor="total-clicks">
            Total Clicks
          </label>
          <div className="flex">
            <Switch className="mr-2" id="total-clicks-on" />
            <Switch id="total-clicks-off" />
          </div>
        </div>
        <div>
          <label className="block mb-2 text-sm font-medium text-gray-900" htmlFor="daily-clicks">
            Daily Clicks
          </label>
          <div className="flex">
            <Switch className="mr-2" id="daily-clicks-on" />
            <Switch id="daily-clicks-off" />
          </div>
        </div>
        <Input id="points" placeholder="Points" />
      </div>
    </div>
  )
}
