/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pmPbAglToOt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Button } from "@/components/ui/button"

export function HomeSection3() {
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="w-[50px]">#</TableHead>
          <TableHead>Social</TableHead>
          <TableHead>Name</TableHead>
          <TableHead>Points</TableHead>
          <TableHead>Hits</TableHead>
          <TableHead>State</TableHead>
          <TableHead>Action</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow className="">
          <TableCell>2.</TableCell>
          <TableCell>Like</TableCell>
          <TableCell>@istego</TableCell>
          <TableCell>4 Point</TableCell>
          <TableCell>45 / 66</TableCell>
          <TableCell>
            <CheckIcon className="text-green-600" />
          </TableCell>
          <TableCell>
            <Button className="bg-white p-1.5" variant="ghost">
              <PencilIcon className="text-gray-600" />
            </Button>
            <Button className="bg-white p-1.5" variant="ghost">
              <PauseIcon className="text-gray-600" />
            </Button>
            <Button className="bg-white p-1.5" variant="ghost">
              <TrashIcon className="text-gray-600" />
            </Button>
          </TableCell>
        </TableRow>
        <TableRow className="">
          <TableCell>3.</TableCell>
          <TableCell>Add</TableCell>
          <TableCell>@check23</TableCell>
          <TableCell>2 Point</TableCell>
          <TableCell>18 / 1045</TableCell>
          <TableCell>
            <XIcon className="text-red-600" />
          </TableCell>
          <TableCell>
            <Button className="bg-white p-1.5" variant="ghost">
              <PencilIcon className="text-gray-600" />
            </Button>
            <Button className="bg-white p-1.5" variant="ghost">
              <PauseIcon className="text-gray-600" />
            </Button>
            <Button className="bg-white p-1.5" variant="ghost">
              <TrashIcon className="text-gray-600" />
            </Button>
          </TableCell>
        </TableRow>
        <TableRow>
          <TableCell>4.</TableCell>
          <TableCell>
            <TwitterIcon className="text-blue-500" />
            Retweet
          </TableCell>
          <TableCell>@makemekkeek</TableCell>
          <TableCell>1 Point</TableCell>
          <TableCell>10 / 45</TableCell>
          <TableCell>
            <CheckIcon className="text-green-600" />
          </TableCell>
          <TableCell>
            <Button className="bg-white p-1.5" variant="ghost">
              <PencilIcon className="text-gray-600" />
            </Button>
            <Button className="bg-white p-1.5" variant="ghost">
              <PauseIcon className="text-gray-600" />
            </Button>
            <Button className="bg-white p-1.5" variant="ghost">
              <TrashIcon className="text-gray-600" />
            </Button>
          </TableCell>
        </TableRow>
        <TableRow>
          <TableCell>5.</TableCell>
          <TableCell>Subscribe</TableCell>
          <TableCell>@x3e</TableCell>
          <TableCell>5 Point</TableCell>
          <TableCell>450 / 648</TableCell>
          <TableCell>
            <CheckIcon className="text-green-600" />
          </TableCell>
          <TableCell>
            <Button className="bg-white p-1.5" variant="ghost">
              <PencilIcon className="text-gray-600" />
            </Button>
            <Button className="bg-white p-1.5" variant="ghost">
              <PauseIcon className="text-gray-600" />
            </Button>
            <Button className="bg-white p-1.5" variant="ghost">
              <TrashIcon className="text-gray-600" />
            </Button>
          </TableCell>
        </TableRow>
        <TableRow className="">
          <TableCell>6.</TableCell>
          <TableCell>
            <FacebookIcon className="text-blue-600" />
            Repost
          </TableCell>
          <TableCell>@samlam</TableCell>
          <TableCell>1 Point</TableCell>
          <TableCell>30 / 65</TableCell>
          <TableCell>
            <XIcon className="text-red-600" />
          </TableCell>
          <TableCell>
            <Button className="bg-white p-1.5" variant="ghost">
              <PencilIcon className="text-gray-600" />
            </Button>
            <Button className="bg-white p-1.5" variant="ghost">
              <PauseIcon className="text-gray-600" />
            </Button>
            <Button className="bg-white p-1.5" variant="ghost">
              <TrashIcon className="text-gray-600" />
            </Button>
          </TableCell>
        </TableRow>
      </TableBody>
    </Table>
  )
}

function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function FacebookIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function PauseIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="14" y="4" width="4" height="16" rx="1" />
      <rect x="6" y="4" width="4" height="16" rx="1" />
    </svg>
  )
}


function PencilIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>
  )
}


function TrashIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}


function TwitterIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
